apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: lb-policy
spec:
  # Announce the LoadBalancer IP
  loadBalancerIPs: true
  interfaces:
    - ^eth[0-9]+
  # Optionally, you can use a serviceSelector to apply this policy only to specific services.
  # For this use case, leaving it out makes it apply to all services that use the IP pool.
