apiVersion: v1
data:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:MEN9qMpE8bVqDS8z,iv:X+/M1e4xuF5olC/dmj3qdNH7+yjCjztrAtG2kGHXGI4=,tag:+ac660QGFsyUAQ5OyFOoDA==,type:str]
kind: Secret
metadata:
    name: mariadb-secret
    namespace: minecraft
sops:
    age:
        - recipient: age1fu3yw8700dznl0xgsrcgghjase8uh94unaj4pjjkh70g7kzv8u3sqcgz4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnd2RBSTBoT01pVGhiN3ph
            RWhidWtPeVkzeGRjM0ZKMmtZaFZtNVV3QnpnCjZzZXVoNDZSb3NMSGxhdFpTUm45
            QU1EVzg3TWtKYVlLaDg0V0J1QUxRUkUKLS0tIE9NVy9VYkVFZ2hMbDRucGxpOTI2
            NmFKRTZ4L0NMelFZTUZEc2FZOGNlQVkKBGozqE5bDD19Ap2xNofwHQdHP4qWik5J
            RnBG8WmQaKTUiTCT7N16b8oRixomUN5zuWHvmUzYuEHZxD0Yw5mBrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T03:33:35Z"
    mac: ENC[AES256_GCM,data:zXL9l8WWDaiSWFADt0ewzgN87PHcZvBG0yU2hI58Hon4C/DQtL7pD9ZRTLwzNosi/QhWWbplSEN2NOJtjGJHbBbRpECl9Fd00WbbZTwZodd33LFLvP6hb8D/pO7po4c5TXMKYoc053A2+R2MtLsL2jZT3pOuCx1771LtheNcu9E=,iv:lVGs+Akt4BU/tdNC0v4rBe8ChwrlHU269PAihteM3GM=,tag:wnXqmwMxuQYcpP3/EOiXyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
