apiVersion: v1
data:
    token: ODMzNDM1MTkzMzpBQUZIWFBNcjFVTkVxQ0F0YXZUbmlKb2NESlNUTV83Nm5Obw==
kind: Secret
metadata:
    creationTimestamp: null
    name: telegram-secrets
    namespace: customer1
