dnsseeder.env.email: sirius-sec@protonmail.com
dnsseeder.env.nodeHostname: zec.sirius-sec.com
dnsseeder.env.seedHostname: sirius-sec.com
dnsseeder.image.repository: electriccoinco/dnsseeder
dnsseeder.image.tag: sha256:9f9ff41101dcfd26c222e51d48cf34a6dc9be918a1702174c9d54e54210c532d
lightwalletd.volumes.data.storageClass: local-path
nodeSelector:
  hostname: highpower
rpc:
  credentials:
    rpcPassword: oC0Z2gcFV2D
    rpcUser: oC0Z2gcFV2D
zebra.volumes.data.storageClass: local-path
