    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer # or Issuer
    metadata:
      name: letsencrypt-cloudflare
    spec:
      acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: sirius_sec@protonmail.com 
        privateKeySecretRef:
          name: letsencrypt-cloudflare-account-key
        solvers:
        - dns01:
            cloudflare:
              apiTokenSecretRef:
                name: cloudflare-api-token-secret
                key: api-token
              



              # Optional: Specify a specific zone if needed, otherwise it will try to discover.
              # zone: example.com
