apiVersion: apps/v1
kind: Deployment
metadata:
  name: multipaper-server-deployment
  namespace: minecraft
spec:
  replicas: 1  # Scale this out as needed
  selector:
    matchLabels:
      app: multipaper-server
  template:
    metadata:
      labels:
        app: multipaper-server
  
    spec:
      securityContext:
        runAsUser: 1000  # Common user ID for Minecraft images (check your image docs)
        runAsGroup: 1000 # Common group ID
        fsGroup: 1000
       
      initContainers:
      - name: copy-config
        image: busybox:1.37 # A minimal image with 'cp' command
        command: ["sh", "-c", "cp -RL /configmap-source/* /writeable-config/"]
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
 
        volumeMounts:
        - name: config-source # Mounts the ConfigMap data as read-only source
          mountPath: /configmap-source
        
        - name: config-writeable # Mounts the EmptyDir/PVC as writable destination
          mountPath: /writeable-config 
      
      - name: download-plugins
        image: curlimages/curl:latest # A minimal image with curl pre-installed
        command: ['sh', '-c', '
          curl -L "https://github.com/ViaVersion/ViaVersion/releases/download/5.5.1/ViaVersion-5.5.1.jar" -o /plugins/Viaversion.jar && 
          curl -L "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot" -o /plugins/floodgate.jar &&
          curl -L "https://github.com/CritterzNFT/Essentials/releases/download/b150542/EssentialsX-2.20.0-dev+11-b150542.jar" -o /plugins/essentials.jar &&
          curl -L "https://github.com/sirius0xdev/lab/releases/download/mcmmo/mcMMO.jar" -o /plugins/mcMMO.jar &&
          curl -L "https://github.com/sirius0xdev/lab/releases/download/luckperms/LuckPerms-Bukkit-5.4.59-7c37629.jar" -o /plugins/luckperms.jar
          ']
        volumeMounts:
          - name: plugins-storage
            mountPath: /plugins
      
      - name: mcmmo-config-copy
        image: busybox:1.37
        command: ["sh", "-c", "cp -RL /mcmmo-config-source/* /writeable-mcmmo-config/"]
        volumeMounts:
          - name: mcmmo-config-source
            mountPath: /mcmmo-config-source
          - name: writeable-mcmmo-config
            mountPath: /writeable-mcmmo-config
      
      - name: essentials-config-copy
        image: busybox:1.37
        
        command: ["sh", "-c", "cp -RL /essentials-config-source/* /writeable-essentials-config/"]
        volumeMounts:
          - name: essentials-config-source 
            mountPath: /essentials-config-source
          - name: writeable-essentials-config 
            mountPath: /writeable-essentials-config 
       
      - name: config-render
        image: bhgedigital/envsubst  # Or any image with envsubst
        envFrom:
        - secretRef:
            name: mariadb-secret       # Loads variables for envsubst to use
        command: ['sh', '-c', 'envsubst < /luckperms-config-source/config.yml > /writeable-luckperms-config/config.yml']
        
        volumeMounts:
        
        - name: luckperms-config-source  
          mountPath: /luckperms-config-source
        
        - name: writeable-luckperms-config 
          mountPath: /writeable-luckperms-config
     
      containers:
      - name: server
        stdin: true
        tty: true 
        image: noevidenz/multipaper:1.20
        
        resources:
          limits:
            memory: 8Gi 
          requests:
            memory: 4Gi 
        envFrom:
          - secretRef:
              name: mariadb-secret  
        env:
          - name: EULA
            value: "true"
          - name: JAVA_TOOL_OPTIONS
            value: "-Xmx1G -DmultipaperMasterAddress=master-headless:35353 -Dproperties.view-distance=16 -Dspigot.settings.velocity=true"
        ports:
          - containerPort: 25575
            name: rcon 
            
        volumeMounts:
          
          - name: config-writeable 
            mountPath: /app
          
          - name: writeable-mcmmo-config 
            mountPath: /app/plugins/mcMMO 
          
          - name: plugins-storage 
            mountPath: /app/plugins
          
          - name: writeable-essentials-config 
            mountPath: /app/plugins/Essentials

          - name: writeable-luckperms-config 
            mountPath: /app/plugins/LuckPerms 
           

      volumes:     # Define the read-only ConfigMap source volume
        - name: config-source
          configMap:
           name: paper-global # The name of your ConfigMap
        
        - name: writeable-mcmmo-config 
          emptyDir: 
        
        - name: mcmmo-config-source
          configMap:
            name: mcmmo-config 
        
        - name: plugins-storage
          emptyDir: {} 
        
        - name: essentials-config-source
          configMap:
            name: essentials-config
        
        - name: writeable-essentials-config 
          emptyDir: 
        
        - name: config-writeable
          emptyDir: {}

        - name: luckperms-config-source 
          configMap:
            name: luckperms-config 
        
        - name: writeable-luckperms-config 
          emptyDir: {} 
      
---

apiVersion: v1
kind: Service
metadata:
  name: rcon-loadbalancer  
  namespace: minecraft
  labels:
    cilium-lb-pool: sirius-ippool 
  annotations: 
    lbipam.cilium.io/sharing-key: sirius-services 
spec:
  type: LoadBalancer
  externalIPs:
    - "5.161.82.129"
  selector:
    app: rcon-service
  ports:
    - protocol: TCP
      port: 25575
      targetPort: 25575
      name: rcon 
