apiVersion: apps/v1
kind: Deployment
metadata:
  name: multipaper-server-deployment
  namespace: minecraft
spec:
  replicas: 1  # Scale this out as needed
  selector:
    matchLabels:
      app: multipaper-server
  template:
    metadata:
      labels:
        app: multipaper-server
  
    spec:
      securityContext:
        runAsUser: 1000  # Common user ID for Minecraft images (check your image docs)
        runAsGroup: 1000 # Common group ID
        fsGroup: 1000
       
      initContainers:
      - name: copy-config
        image: busybox:1.36 # A minimal image with 'cp' command
        command: ["sh", "-c", "cp -RL /configmap-source/* /writeable-config/"]
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
 
        volumeMounts:
        - name: config-source # Mounts the ConfigMap data as read-only source
          mountPath: /configmap-source
        
        - name: config-writeable # Mounts the EmptyDir/PVC as writable destination
          mountPath: /writeable-config 
      
      - name: download-plugins
        image: curlimages/curl:latest # A minimal image with curl pre-installed
        command: ['sh', '-c', '
          curl -L "https://github.com/ViaVersion/ViaVersion/releases/download/5.5.1/ViaVersion-5.5.1.jar" -o /plugins/Viaversion.jar && 
          curl -L "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot" -o /plugins/floodgate.jar &&
          curl -L "https://github.com/CritterzNFT/Essentials/releases/download/b150542/EssentialsX-2.20.0-dev+11-b150542.jar" -o /plugins/essentials.jar 
          ']
        volumeMounts:
          - name: plugins-storage
            mountPath: /plugins
      
      containers:
      - name: server
        image: noevidenz/multipaper:1.20
        
        resources:
          limits:
            memory: 8Gi 
          requests:
            memory: 4Gi 
        
        env:
        - name: EULA
          value: "true"
        - name: JAVA_TOOL_OPTIONS
          value: "-Xmx1G -DmultipaperMasterAddress=master-headless:35353 -Dproperties.view-distance=16 -Dspigot.settings.velocity=true"
        
        volumeMounts:
          - name: config-writeable 
            mountPath: /app
           
          - name: plugins-storage 
            mountPath: /app/plugins 

      volumes:     # Define the read-only ConfigMap source volume
        - name: config-source
          configMap:
           name: paper-global # The name of your ConfigMap
        
        - name: plugins-storage
          emptyDir: {} 
             
        # Define a writable volume (use EmptyDir for temporary config or PVC for permanent config)
        
        - name: config-writeable
          emptyDir: {} 
            
             

