apiVersion: v1
kind: ConfigMap
metadata:
  name: zebrad-config
  namespace: zcash 
data:
  zebrad.toml: | 

   [network]
   network = "Mainnet"
   listen_addr = "0.0.0.0"
   cache_dir = "/var/cache/zebrad-cache"


   [rpc]

   listen_addr = "0.0.0.0:8232" # Mainnet

   cookie_dir = "/var/cache/zebrad-cache"


   enable_cookie_auth = false 

   [state]
   cache_dir = "/var/cache/zebrad-cache"

   [tracing]
   use_color = true


   [metrics]

   endpoint_addr = "0.0.0.0:9999" # Prometheus

   [health]
   # Health endpoints are disabled by default. To enable them, uncomment the
   # listen_addr below. These endpoints are intended for Kubernetes probes and
   # load balancers.

   # listen_addr = "0.0.0.0:8080" # /healthy and /ready
   # min_connected_peers = 1
   # ready_max_blocks_behind = 2
   # enforce_on_test_networks = false

   [mining]
    # If you are going to use Zebra as a backend for a mining pool, set your mining
    # address.

    # miner_address = "your_mining_address"
