apiVersion: v1
kind: Service
metadata:
  name: zebrad-service
  namespace: zcash 
spec:
  type: Clusterip 
  selector:
    app: zebrad  
  ports:
    - port: 8232
      targetPort: 8232
      protocol: TCP
      name: rpc
