    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: wildcard-sirius-trading-com
      namespace: linkding # Or your application's namespace
    spec:
      secretName: wildcard-sirius-trading-com-tls 
      issuerRef:
        name: letsencrypt-cloudflare
        kind: ClusterIssuer # or Issuer
      commonName: "*.sirius-sec.com"
      dnsNames:
      - "*.sirius-sec.com"
      - "sirius-sec.com"
