
apiVersion: batch/v1
kind: CronJob 
metadata:
  name: news-analyst-gemini
  namespace: newsbot

spec:
  schedule: "15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: analyst-gemini
              image: siriussec/gemini_news_summarizer:0.1
              
              env:
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: news-db-secret 
                      key: password 
              envFrom:
                - configMapRef:
                    name: news-app-config
                
                
                - secretRef:
                    name: gemini-apikey
          restartPolicy: OnFailure 
