apiVersion: batch/v1
kind: CronJob
metadata:
  name: analyst-gemma
  namespace: newsbot 
spec:
  schedule: "15 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: ollama-storage
              persistentVolumeClaim:
                claimName: ollama-storage


          initContainers:
            - name: model-puller
              image: ollama/ollama:latest
              volumeMounts:
                - name: ollama-storage
                  mountPath: /root/.ollama
              command: ["/bin/sh", "-c"]
              args: ["ollama serve & sleep 5 && ollama pull qwen3:30b-a3b"]

        
            - name: ollama-sidecar
              image: ollama/ollama:latest
              restartPolicy: Always          
              env:
                - name: OLLAMA_DEBUG
                  value: "2"
                - name: OLLAMA_LOG_LEVEL
                  value: "DEBUG"
              ports:
                - containerPort: 11434
              volumeMounts:
                - name: ollama-storage
                  mountPath: /root/.ollama
              resources:
                limits:
                  nvidia.com/gpu: 1
          containers:
            - name: analyst
              image: siriussec/summarizerlocal:3.4
              imagePullPolicy: Always
              env:
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: news-user-password
                      key: password
              envFrom:
                - configMapRef:
                    name: gemma-config 

          restartPolicy: OnFailure


