
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newsbot
resources:
  - configmap.yaml
  - gemini-apikey.yaml 
  - news-user-db-secret.yaml
  - analyst-gemini-cronjob.yaml
  - scraper-cronjob.yaml
  - scrapy-urls-configmap.yaml
  - scrapy-configmap.yaml
  - telebot-cronjob.yaml
  - telebot-secret.yaml 
  # - gemma-configmap.yaml
  # - analyst-cronjob.yaml
 # - ollama-storage.yaml

