apiVersion: v1
data:
    password: ENC[AES256_GCM,data:lC6DvbhPveAHRuxmXW/xUe9a5dY=,iv:hQbRSdhfZrMSQJdogcCPbsQ5BrAhNdXQOs6pg5VdsW0=,tag:x9Uwga0SHhOOxslMnlBqwg==,type:str]
kind: Secret
metadata:
    name: new-user-db-secret
sops:
    age:
        - recipient: age1fu3yw8700dznl0xgsrcgghjase8uh94unaj4pjjkh70g7kzv8u3sqcgz4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRGJTNG9CYW5MUGVJdkZS
            WENNc05vOTB6L0VnT1AwUUFWbGIzNXpsUEVZClpXTkw2SnJqVXpSUzJ0ZFczd1I4
            NjJNMVFPNEV5dDZFemxsRHBuK2s1MGMKLS0tIDVKM3N6MGRIRy9ONFRPWHV1Q056
            dWJmMXBUa3NZVnVJT1B3Rzc3SWRnRzQKqDjEEbl6N1MD8WXxoMx6DtiBtc4KvFFR
            x7wburc+THfwuFTbGP/hZc081/My8KGTNxZRKQdnZUnNTKL4iZ170w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T19:56:59Z"
    mac: ENC[AES256_GCM,data:Ef/RpUC9u8MMzKGuomZi3XeiHWu5vOFh7N3JygBRQGRHIgO5WEsPnraoMO9D9wh3o7d4/vH3KBBeo1UjPmBTTJ7HDp6mTP2tSmvjG/8kgQNQqcBxuxDUZYFHWXrkTRjg4604VqIHoYNzEf2SuRURhuNQQQro9jcOmVF4vAwELJs=,iv:ifiqXmrsuEbaFFi4Cp1Wa0j87DweEIzu3P6ZiqFGhJ8=,tag:9h0Al5lnro7YOoPPzjCjeg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
