apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: newsbot-db
  namespace: newsbot 
spec:
  managed:
    roles:
      name: news_app
      ensure: present
      login: true
      passwordSecret:
        name: news-user-password 
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:15.2
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: news_app_db
      owner: news_app 
      secret:
        news-user-password 




