apiVersion: v1
data:
    token: ENC[AES256_GCM,data:ojU9HF7SVHHORfhKTdd0em3EU3weDw0z7gX0tj/uIMHpfzLyUv/UxHP4lgSwYpKXaUW74/xCtGuIJsBKZa5FAJ+7DEDOcdJEzmObjAzYfKHr95/ay5DXtQ==,iv:qKPnEY5pZa6ZliLANCpoNsolWOqACRtSEne136QSJ1o=,tag:WLSk4Yyo8M4D2B36mhJ+iQ==,type:str]
kind: Secret
metadata:
    name: telebot-token
    namespace: newsbot
sops:
    age:
        - recipient: age1fu3yw8700dznl0xgsrcgghjase8uh94unaj4pjjkh70g7kzv8u3sqcgz4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZ1pZSXZZVXVOTGc5cERt
            bzNsaVI1RHVVRjUzdWlQYlQxQStyclNVb0JNCkZOc2Jmc1Q2STNzaUlDdDRzRmIz
            TmYzUmg4UWVaZzBXVFc2Z2VhZTgzNlkKLS0tIGQzc2xNbG13b1p1Tk1Eb09Yc1ZT
            WUpqZ1RvU0ZmWTJ1cVFKcDhTNjN0VU0KhbGc+5BASm1QPS+pgSqPh3FTq8p7z3rj
            QOsoL2pS6sq325DfiuDFvPwR91KIt7A3x/4qDXS0BEKUdx6UqA8Fpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T18:38:34Z"
    mac: ENC[AES256_GCM,data:AD4pI/HeGXSC+HuFYLnWxUkRbfArO6YPhNu+Ucbh66VCOGzxGZptbCQMxHUXjzCnvA9N5w4KGVY5hcdaTDyxuggjmYcOM/aLK2dgTisfU07OFDURrdInSYXmIiC5sdabapey21+NmIvOwiDKYTwE5MQsued94RoWqSZ8d4AeHIY=,iv:RCq9xUKZ6P2YTcCm2RiJ5db/JVJZtDQIhA9HzqaU0BE=,tag:c4iOXl1lW2qA7DMmreQMCw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
