apiVersion: v1
kind: ConfigMap 
metadata:
  name: velocity-config
  namespace: minecraft 
data:
  velocity.toml: |
    config-version = "2.7"
    
    bind = "0.0.0.0:25577"

    motd = "<#09add3>A Velocity Server"

    show-max-players = 500

    online-mode = true  

    force-key-authentication = true

    prevent-client-proxy-connections = false

    player-info-forwarding-mode = modern  

    forwarding-secret = "w5A76DwhYVb2cTTLLkH4Pqmanr7xNjmb"

    announce-forge = false

    kick-existing-players = false

    ping-passthrough = "DISABLED"

    sample-players-in-ping = false

    enable-player-address-logging = true

    [servers]
    Main = "master-headless" 

    try = [
        "Main"   
    ]
    [forced-hosts]
    
    "minecraft.sirius-sec.com" = [
        "Main"
    ]
    

    [advanced]
    compression-threshold = 256

    compression-level = -1

    login-ratelimit = 3000

    connection-timeout = 5000

    read-timeout = 30000

    haproxy-protocol = false

    tcp-fast-open = true 

    bungee-plugin-message-channel = true

    show-ping-requests = false

    failover-on-unexpected-server-disconnect = true

    announce-proxy-commands = true

    log-command-executions = false

    log-player-connections = true

    accepts-transfers = false

    enable-reuse-port = false

    command-rate-limit = 50

    forward-commands-if-rate-limited = true

    kick-after-rate-limited-commands = 0

    tab-complete-rate-limit = 10

    kick-after-rate-limited-tab-completes = 0

    [query]
    enabled = false

    port = 25565

    # This is the map name that is reported to the query services.
    map = "Velocity"

    show-plugins = false
  config.yml: |
    
    bedrock:
      address: 0.0.0.0
      port: 19132
      clone-remote-port: false
      motd1: "Geyser"
      motd2: "Another Geyser server."
      server-name: "Geyser"
      compression-level: 3
      enable-proxy-protocol: false
    remote: 
        address: master-headless     
        port: 35353 
        auth-type: floodgate   
        allow-password-authentication: true
    use-proxy-protocol: false
    forward-hostname: false

    floodgate-key-file: /server/plugins/floodgate/key.pem

    saved-user-logins:
      - MidFriend3407
      - ThisOtherExampleUsernameShouldAlsoBeLongEnough

    pending-authentication-timeout: 120

    command-suggestions: true

    passthrough-motd: false
    passthrough-protocol-name: false
    passthrough-player-counts: false
    legacy-ping-passthrough: false
    ping-passthrough-interval: 3

    forward-player-ping: false

    max-players: 1000

    debug-mode: false

    allow-third-party-capes: true

    allow-third-party-ears: false

    show-cooldown: title

    show-coordinates: true

    disable-bedrock-scaffolding: false

    always-quick-change-armor: false

    emote-offhand-workaround: "disabled"


    cache-images: 0

    allow-custom-skulls: true

    max-visible-custom-skulls: 128

    custom-skull-render-distance: 32

    add-non-bedrock-items: true

    above-bedrock-nether-building: false

    force-resource-packs: true

    xbox-achievements-enabled: false

    log-player-ip-addresses: true

    notify-on-new-bedrock-update: true

    metrics:
      enabled: true
      uuid: 96e45ad9-512d-4907-8a92-1ec5ebed6d5f


    scoreboard-packet-threshold: 20

    enable-proxy-connections: false

    mtu: 1400

    use-direct-connection: true

    config-version: 4
    
