apiVersion: v1
kind: ConfigMap
metadata:
  name: prosody-config
  namespace: prosody
data:
  01-modules.cfg.lua: | # Added the pipe character
    modules_enabled = {
     "roster";
      "saslauth";
      "blocklist";
          "bookmarks";
          "carbons";
          "dialback";
          "limits";
          "pep";
          "private";
          "smacks";
          "vcard4";
          "vcard_legacy";

          "account_activity";
          "cloud_notify";
          "csi_simple";
          "invites";
          "invites_adhoc";
          "invites_register";
          "ping";
          "register";
          "time";
          "uptime";
          "version";

        "admin_adhoc";
        "admin_shell";

          "groups";
          "mimicking";
          "proxy65";
          "s2s_bidi";
          "watchregistrations";
      }

  05-vhost.cfg.lua: | # Added the pipe character
    local domain = os.getenv("DOMAIN")
    local domain_http_upload = os.getenv("DOMAIN_HTTP_UPLOAD") or "upload." .. domain
    local domain_muc = os.getenv("DOMAIN_MUC") or "conference." .. domain
    local domain_proxy = os.getenv("DOMAIN_PROXY") or "proxy." .. domain
    local domain_pubsub = os.getenv("DOMAIN_PUBSUB") or "pubsub." .. domain

    c2s_direct_tls_ssl = {
      certificate = "certs/" .. domain .. "/tls.crt";
      key = "certs/" .. domain .. "/tls.key";
    }
    c2s_direct_tls_ports = { 5223 }

    https_ssl = {
        certificate = "certs/" .. domain_http_upload .. "/tls.crt";
        key = "certs/" .. domain_http_upload .. "/tls.key";
    }

    VirtualHost (domain)
    disco_items = {
        { domain_http_upload },
    }

    Component (domain_http_upload) "http_file_share"
        http_file_share_expires_after = 60 * 60 * 24 * 7
        local size_limit = os.getenv("HTTP_FILE_SHARE_SIZE_LIMIT") or 10 * 1024 * 1024
        http_file_share_size_limit = size_limit
        http_file_share_daily_quota = os.getenv("HTTP_FILE_SHARE_DAILY_QUOTA") or 10 * size_limit

    Component (domain_muc) "muc"
        name = "Prosody Chatrooms"
        restrict_room_creation = false
        max_history_messages = 20
        modules_enabled = {
            "muc_mam",
            "vcard_muc"
        }

    Component (domain_proxy) "proxy65"
        proxy65_address = domain_proxy
        proxy65_acl = { domain }

    Component (domain_pubsub) "pubsub"
