apiVersion: v1
kind: ConfigMap
metadata:
  name: prosody-config
  namespace: prosody
data:
  # Paste content of 01-modules.cfg.lua here
  01-modules.cfg.lua: |
    -- your 01-modules content...
    modules_enabled = {
      "roster";
      "saslauth";
      "blocklist"
      "blocklist"; -- Allow users to block communications with other users
		  "bookmarks"; -- Synchronise the list of open rooms between clients
		  "carbons"; -- Keep multiple online clients in sync
		  "dialback"; -- Support for verifying remote servers using DNS
		  "limits"; -- Enable bandwidth limiting for XMPP connections
		  "pep"; -- Allow users to store public and private data in their account
		  "private"; -- Legacy account storage mechanism (XEP-0049)
		  "smacks"; -- Stream management and resumption (XEP-0198)
		  "vcard4"; -- User profiles (stored in PEP)
		  "vcard_legacy"; -- Conversion between legacy vCard and PEP Avatar, vcard

	    -- Nice to have
		  "account_activity"; -- Record time when an account was last used
		  "cloud_notify"; -- Push notifications for mobile devices
		  "csi_simple"; -- Simple but effective traffic optimizations for mobile devices
		  "invites"; -- Create and manage invites
		  "invites_adhoc"; -- Allow admins/users to create invitations via their client
		  "invites_register"; -- Allows invited users to create accounts
		  "ping"; -- Replies to XMPP pings with pongs
		  "register"; -- Allow users to register on this server using a client and change passwords
		  "time"; -- Let others know the time here on this server
		  "uptime"; -- Report how long server has been running
		  "version"; -- Replies to server version requests

  	  -- Admin interfaces
	  	"admin_adhoc"; -- Allows administration via an XMPP client that supports ad-hoc commands
	  	"admin_shell"; -- Allow secure administration via 'prosodyctl shell'

	    -- HTTP modules
		  --"bosh"; -- Enable BOSH clients, aka "Jabber over HTTP"
		  --"http_openmetrics"; -- for exposing metrics to stats collectors
		  --"websocket"; -- XMPP over WebSockets

	    -- Other specific functionality
		  "groups"; -- Shared roster support
		  "mimicking"; -- Prevent address spoofing
		  "proxy65"; -- Enables a file transfer proxy service which clients behind NAT can use
		  "s2s_bidi"; -- Bi-directional server-to-server (XEP-0288)
		  "watchregistrations"; -- Alert admins of registrations
      }

  # Paste content of 05-vhost.cfg.lua here (from the GitHub link you shared)
  05-vhost.cfg.lua: |
    -- This file configures the main domain for Prosody

    local domain = os.getenv("DOMAIN")
    local domain_http_upload = os.getenv("DOMAIN_HTTP_UPLOAD") or "upload." .. domain
    local domain_muc = os.getenv("DOMAIN_MUC") or "conference." .. domain
    local domain_proxy = os.getenv("DOMAIN_PROXY") or "proxy." .. domain
    local domain_pubsub = os.getenv("DOMAIN_PUBSUB") or "pubsub." .. domain

    -- XEP-0368: SRV records for XMPP over TLS
    -- https://compliance.conversations.im/test/xep0368/
    c2s_direct_tls_ssl = {
	  certificate = "certs/" .. domain .. "/tls.crt";
	  key = "certs/" .. domain .. "/tls.key";
    }
    c2s_direct_tls_ports = { 5223 }

    -- https://prosody.im/doc/certificates#service_certificates
    -- https://prosody.im/doc/ports#ssl_configuration
    https_ssl = {
	    certificate = "certs/" .. domain_http_upload .. "/tls.crt";
	    key = "certs/" .. domain_http_upload .. "/tls.key";
    }

    VirtualHost (domain)
    disco_items = {
        { domain_http_upload },
    }

    -- Set up a http file upload because proxy65 is not working in muc
    Component (domain_http_upload) "http_file_share"
	    http_file_share_expires_after = 60 * 60 * 24 * 7 -- a week in seconds
	    local size_limit = os.getenv("HTTP_FILE_SHARE_SIZE_LIMIT") or 10 * 1024 * 1024 -- Default is 10MB
	    http_file_share_size_limit = size_limit
	    http_file_share_daily_quota = os.getenv("HTTP_FILE_SHARE_DAILY_QUOTA") or 10 * size_limit -- Default is 10x the size limit

    Component (domain_muc) "muc"
	    name = "Prosody Chatrooms"
	    restrict_room_creation = false
	    max_history_messages = 20
	    modules_enabled = {
		    "muc_mam",
		    "vcard_muc"
	    }

    -- Set up a SOCKS5 bytestream proxy for server-proxied file transfers
    Component (domain_proxy) "proxy65"
	    proxy65_address = domain_proxy
	    proxy65_acl = { domain }

    -- Implements a XEP-0060 pubsub service.
    Component (domain_pubsub) "pubsub"
