apiVersion: v1
kind: ConfigMap
metadata:
  name: prosody-config
  namespace: prosody
data:
  01-modules.cfg.lua: | # Added the pipe character
    modules_enabled = {
     "roster";
      "saslauth";
      "blocklist";
          "bookmarks";
          "carbons";
          "dialback";
          "limits";
          "pep";
          "private";
          "smacks";
          "vcard4";
          "vcard_legacy";

          "csi_simple";
          "invites";
          "invites_adhoc";
          "invites_register";
          "ping";
          "register";
          "time";
          "uptime";
          "version";

        "admin_adhoc";
        "admin_shell";

          "groups";
          "mimicking";
          "proxy65";
          "s2s_bidi";
          "watchregistrations";
      }
  02-storage.cfg.lua: |
    default_storage = "sql"

    sql = {
      driver = os.getenv("DB_DRIVER") or "SQLite3";
      database = os.getenv("DB_DATABASE") or "prosody.sqlite";
      host = os.getenv("DB_HOST");
      port = os.getenv("DB_PORT");
      username = os.getenv("DB_USERNAME");
      password = os.getenv("DB_PASSWORD");
    }

    -- make 0.10-distributed mod_mam use sql store
    archive_store = "archive2" -- Use the same data store as prosody-modules mod_mam

    storage = {
      -- this makes mod_mam use the sql storage backend
      archive2 = "sql";
    }

    -- https://modules.prosody.im/mod_mam.html
    archive_expires_after = "1y"

    http_max_content_size = os.getenv("HTTP_MAX_CONTENT_SIZE") or 1024 * 1024 * 10 -- Default is 10MB
  
  03-e2e.cfg.lua: |
    local stringy = require "stringy" 

    e2e_policy_chat = os.getenv("E2E_POLICY_CHAT") or "required"
    e2e_policy_muc = os.getenv("E2E_POLICY_MUC") or "required"

    local whitelist = os.getenv("E2E_POLICY_WHITELIST") or ""
    e2e_policy_whitelist = stringy.split(whitelist, ", ")

    e2e_policy_message_optional_chat = "For security reasons, OMEMO, OTR or PGP encryption is STRONGLY recommended for conversations on this server."
    e2e_policy_message_required_chat = "For security reasons, OMEMO, OTR or PGP encryption is required for conversations on this server."
    e2e_policy_message_optional_muc = "For security reasons, OMEMO, OTR or PGP encryption is STRONGLY recommended for MUC on this server."
    e2e_policy_message_required_muc = "For security reasons, OMEMO, OTR or PGP encryption is required for MUC on this server."
  



  05-vhost.cfg.lua: | # Added the pipe character
    local domain = os.getenv("DOMAIN")
    local domain_http_upload = os.getenv("DOMAIN_HTTP_UPLOAD") or "upload." .. domain
    local domain_muc = os.getenv("DOMAIN_MUC") or "conference." .. domain
    local domain_proxy = os.getenv("DOMAIN_PROXY") or "proxy." .. domain
    local domain_pubsub = os.getenv("DOMAIN_PUBSUB") or "pubsub." .. domain

    c2s_ssl = {
      certificate = "certs/" .. domain .. "/tls.crt";
      key = "certs/" .. domain .. "/tls.key";
    }
    
    c2s_require_encryption = true
       c2s_direct_tls_ssl = {
        certificate = "certs/" .. domain .. "/tls.crt";
        key = "certs/" .. domain .. "/tls.key";
    │ }
      c2s_direct_tls_ports = {5223} 
    
      https_ssl = {
        certificate = "certs/" .. domain_http_upload .. "/tls.crt";
        key = "certs/" .. domain_http_upload .. "/tls.key";
      }

    VirtualHost (domain)
    disco_items = {
        { domain_http_upload },
    }

    Component (domain_http_upload) "http_file_share"
        http_file_share_expires_after = 60 * 60 * 24 * 7
        local size_limit = os.getenv("HTTP_FILE_SHARE_SIZE_LIMIT") or 10 * 1024 * 1024
        http_file_share_size_limit = size_limit
        http_file_share_daily_quota = os.getenv("HTTP_FILE_SHARE_DAILY_QUOTA") or 10 * size_limit

    Component (domain_muc) "muc"
        name = "Prosody Chatrooms"
        restrict_room_creation = false
        max_history_messages = 20
        modules_enabled = {
            "muc_mam",
            "vcard_muc"
        }

    Component (domain_proxy) "proxy65"
        proxy65_address = domain_proxy
        proxy65_acl = { domain }

    Component (domain_pubsub) "pubsub"
