apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prosody
  name: prosody
  namespace: prosody 
spec:
  relicas: 1
  selector:
    matchLabels:
      app: prosody 
  strategy: rollingRealease
  template:
    metadata:
      labels:
        app: prosody
    spec:
      containers:
        - image: prosodyim/prosody:13.0
          name: prosody
          env:
            - name: PROSODY_VIRTUAL_HOSTS
              value: localhost 
          ports:
            - containerPort: 5222
            -  containerPort: 5269
          volumeMounts:
            - mountPath: /var/lib/prosody
            - mountPath: /etc/prosody
            - mountPath: /var/log/prosody

      volumes:
        - name: prosody-data
          persistentVolumeClaim:
            claimName: prosody-data 
