apiVersion: v1

data:
  prosody.cfg.lua:
    "admins = { \"sirius@sirius-sec.com\" }\n\nmodules_enabled = {\n\n\t\t\"disco\";\n\t\t\"roster\";\n\t\t\"saslauth\";\n\t\t\"tls\";\n\n\t\t\"blocklist\";\n\t\t\"bookmarks\";\n\t\t\"carbons\";\n\t\t\"dialback\";\n\t\t\"limits\";\n\t\t\"pep\";\n\t\t\"private\";\n\t\t\"smacks\";
    \n\t\t\"vcard4\"; \n\t\t\"vcard_legacy\"; \n\n\t\t\"account_activity\"; \n\t\t\"cloud_notify\";
    \n\t\t\"csi_simple\";\n\t\t\"invites\"; \n\t\t\"invites_adhoc\"; \n\t\t\"invites_register\";
    \n\t\t\"ping\"; \n\t\t\"register\"; \n\t\t\"time\"; \n\t\t\"uptime\";\n  \t\"version\";
    \n\n\t\t\"admin_adhoc\"; \n\t\t\"admin_shell\";\n\n\t\t\"proxy65\"; \t\t\n\t  \"s2s_bidi\";\n\n\t\t\"watchregistrations\";
    \n}\n\n\n\nmodules_disabled = {\n\t \"offline\"; \n}\n\n\n\ns2s_secure_auth =
    true\n\n\nlimits = {\n\tc2s = {\n\t\trate = \"10kb/s\";\n\t};\n\ts2sin = {\n\t\trate
    = \"30kb/s\";\n\t};\n}\n\n\nauthentication = \"internal_hashed\"\n\n\n\nlog =
    {\n\tinfo = \"*syslog\"; -- Uncomment this for logging to syslog\n}\n\n\ncertificates
    = \"certs\"\n\n\nVirtualHost \"localhost\"\n\n\n\n"
kind: ConfigMap
metadata:
  name: prosody-config
  namespace: prosody
