apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prosody
  namespace: prosody
spec:
  replicas: 1
  serviceName: "prosody-headless"
  selector:
    matchLabels:
      app: prosody
  template:
    metadata:
      labels:
        app: prosody
    spec:
      # This schedules the pod exclusively on the labeled node.
      nodeSelector:
        network-role: lb-node
      # Pod uses the host's network stack
      hostNetwork: true
      # Required when using hostNetwork to ensure cluster DNS resolution works
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: prosody
          image: sarasmiseth/prosody
          env:
            - name: DOMAIN
              value: sirius-sec.com
          ports:
            - containerPort: 5000
              name: file-share
            - containerPort: 5223
              name: legacy-ssl
            - containerPort: 5222
              name: xmpp-c2s
            - containerPort: 5269
              name: xmpp-s2s
            - containerPort: 5347
              name: xmpp-componant
            - containerPort: 5280
              name: prosody-http
            - containerPort: 5281
              name: prosody-https
          volumeMounts:
            - name: prosody-config
              mountPath: /etc/prosody/prosody.cfg.lua
              subPath: prosody.cfg.lua
            - name: prosody-data
              mountPath: usr/local/var/lib/prosody
            - name: prosody-certs
              mountPath: /usr/local/games/prosody/certs
      volumes:
        - name: prosody-config
          configMap:
            name: prosody-config

        - name: prosody-certs
          secret:
            secretName: prosody-cert
            defaultMode: 0444

        - name: prosody-data
          persistentVolumeClaim:
            claimName: prosody-data
  volumeClaimTemplates:
    - metadata:
        name: prosody-data
        namespace: prosody
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path
