apiVersion: apps/v1
kind: Deployment
metadata:
  name: geysermc-deployment
  namespace: minecraft 
  labels:
    app: geysermc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geysermc
  template:
    metadata:
      labels:
        app: geysermc
    spec:
      containers:
      - name: geysermc-container
        image: siriussec/geysermc-custom:latest  
        ports:
        - containerPort: 19132
          name: bedrock-udp
          protocol: UDP
        command: ["/bin/sh", "-c"]
        args:
          # 1. Copy the read-only file to the writable volume location
          # 2. Start the Java app, pointing it to the writable location
          - cp /config-source/config.yml /app/config.yml; 
            java -Dgeyser.datadir=/geyser-data -jar geyser.jar
       
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: floodgate-key-volume
          mountPath: /app/config/key.pem # Ensure this is the correct path Geyser expects
          subPath: key.pem
        
        - name: geyser-data-volume
          mountPath: /geyser-data
        
        - name: geyser-config-volume 
          mountPath: /config-source
      
      volumes:
       
      - name: floodgate-key-volume
        secret:
           secretName: geyser-floodgate-key # Name of the secret you created in Step 2
           defaultMode: 0400 
      
      - name:  geyser-data-volume
        emptyDir: {}  
      
      - name: geyser-config-volume
        configMap:
          name: geyser-config 
      

