
apiVersion: v1
kind: Service
metadata:
  name: geyser-loadbalancer 
  namespace: minecraft  
  labels:
    cilium-lb-pool: sirius-ippool
  annotations:
    lbipam.cilium.io/sharing-key: sirius-services
spec:
  type: LoadBalancer
  externalIPs:
    - "5.161.82.129"
  externalTrafficPolicy: Cluster
  selector:
    app: geysermc    
  ports:
    - name: proxy 
      protocol: UDP 
      port: 19132
      targetPort: 19132 
