zcashd:
    enabled: ENC[AES256_GCM,data:OO1/dcs=,iv:LjhxIy5wMxEBn1cIIHn7CRmwM9EpaP0ydH5Eq3EdWpo=,tag:DVxIRk+BMgJ0jXlYuXLP0w==,type:bool]
    name: ENC[AES256_GCM,data:mrnqycQl,iv:5f7zaKJpHLXCoJBLSCgVvfL/RwNmiC6G+QZUjhiXgBQ=,tag:hRzTVeNjU+LTL9Zj3ACyxA==,type:str]
    testnet: ENC[AES256_GCM,data:eGmDz28=,iv:GbMOqmMM4LsxDfVFHtKQkSCMgonbsg1P/Km+SwXhmXQ=,tag:ui1YxMEo/Qwl/ehNQrgw3g==,type:bool]
    image:
        repository: ENC[AES256_GCM,data:s7Qgg0UEPUelJqTDcaMYNERwuI+d,iv:62bzto9oBkwISIV6GHYkJxQJX5IqpLZ180Wdtynwans=,tag:HAVNtyjJXlW2GscmTGkwFQ==,type:str]
        tag: ENC[AES256_GCM,data:4RMyge1f,iv:HVNEXAoa0rVEkS0BkYhu6dWVGeAq1coxZEtaqZY+Weg=,tag:xuLl8Xa893QtMRimcm3/uw==,type:str]
        pullPolicy: ENC[AES256_GCM,data:GpgReDmA0qNOcG8G,iv:a6fbKXc9jbaBqOEA4fefCgYMF/jyttMnew2vnTsif+4=,tag:El7vIMWgZYePpeNwAFfhdw==,type:str]
    replicas: ENC[AES256_GCM,data:mg==,iv:lESEBxLXJ4J3aUaOMD3qbllZfeNwcu5ClUp6T2JqFdM=,tag:9okbOC4Su+SL/Kq6b8RRUA==,type:int]
    reindex: ENC[AES256_GCM,data:5/As6h4=,iv:j+PcoP+FnHBOg0G0I5fhp3pslxpuKru7Y7GtVZt1ejY=,tag:Kzx+4hZ5KS+MxZylz7JSNQ==,type:bool]
    nodes:
        - ENC[AES256_GCM,data:KY+bBnkGdo8ZsvHRl7c=,iv:qTeDEtnjNNaBeAy57MeQfPQ3rT0nZ35Ne/DbwwIMYkE=,tag:ljTVgJZhjcPuqvbZFsVZgQ==,type:str]
    additionalArgs: []
    volumes:
        data:
            size: ENC[AES256_GCM,data:Crz1Xdg=,iv:+ReA1F3xZ4e8f9W4ygqm/yxP9sAx28tzU//2OkvZxF4=,tag:altZfUzV2V83QF7IKC8kZA==,type:str]
            storageClass: ENC[AES256_GCM,data:O8UqogMvEw14YQ==,iv:VUCaE3RpGU75irfEUeWDXLu16d65jaaqtLXcNCDp5kQ=,tag:NUghXeHz3OF213ohJG2fkg==,type:str]
            accessMode: ENC[AES256_GCM,data:+dSiCsOafQSeD7NW7g==,iv:CsSUWGPH2EhTOvYNRY4rxCSjWxMsAxrlLmvhF4DLirM=,tag:M2QgfCSM98qyAFxhBppcMg==,type:str]
    service:
        type: ENC[AES256_GCM,data:T8HeLe+Qonuj,iv:iIwNVKNJ78APS78yTT6Mx9xMVTITBqS7kFoEIUpU4zY=,tag:TiKdlTkylZ3HlHngxKI8qg==,type:str]
    requests: {}
    #ENC[AES256_GCM,data:r1YHvTkra8HwSw==,iv:HVZcNT+k09O6ffzV++T112eGjEqWFHXOM5w/Z5f6LQs=,tag:ACXFVIzU4UR/qnXQ1rOJ1A==,type:comment]
    #ENC[AES256_GCM,data:8FOBtnaYMw7C,iv:/XPrho28ToocDDk/Vapr2neQwISPGaVcEWeebggnJ8k=,tag:v87HGCCsDG6qlf0wDLSpBA==,type:comment]
    #ENC[AES256_GCM,data:RZH6uaAs9eMA3n4n1L6fwA==,iv:41cIpDSU/soCRUwf6NHO4UB9A6Dv8afjt8FIjJ1E9WU=,tag:YKtZkXhmaFCSBRnHR65ENA==,type:comment]
    #ENC[AES256_GCM,data:UY4oQU4P8g==,iv:Y39Vc3lU3AanptQXAU4EWAUa16xbLk27v33GGm0Y+mY=,tag:qX9lKDFMTA8c1OeKSxAUJg==,type:comment]
    #ENC[AES256_GCM,data:sxrxR0FqVZha51mmEA==,iv:TF1IdhpBmh35sjq9EqWlOIiUe6PJgdCZwcgQq+FulhM=,tag:9J0W2urb+s0ujtGdf3L7BQ==,type:comment]
zebra:
    enabled: ENC[AES256_GCM,data:tdl8QQ==,iv:Tw7IXRAAiwzRwzwlg7AQJT7nt2RDAB7c4jSS49h7F5E=,tag:U1rZhpFOhASQ9D8Kqz+8Aw==,type:bool]
    name: ENC[AES256_GCM,data:4lU24+w=,iv:O6+PUAhKEFZ7p4rqkwarzJUge+FF0w+O8b2ZEjfpMr4=,tag:jpixPyGrOe2fWsfmntAQ5g==,type:str]
    testnet: ENC[AES256_GCM,data:koyBTMY=,iv:xtP4m3HDeGnu6VqTcNPc6msdcVesxQI2YeBTM3XN04k=,tag:7DT3zu0EIrO5bi32Z9obAA==,type:bool]
    image:
        repository: ENC[AES256_GCM,data:NDPnGz7OH10KSA==,iv:f6Aq3bRNC+30ZnwwJf+TMTssKpjtclvHkseWHiXHgPQ=,tag:8/y/Rlx9ELOyACtgp6H1nA==,type:str]
        tag: ENC[AES256_GCM,data:TxB5s6a5,iv:RWLUJhAL0vIGy5WTCR8Obi6JhxLHIm7Pcu5vwwltUZA=,tag:XrerDqL5qRexFILtKUMtTQ==,type:str]
        pullPolicy: ENC[AES256_GCM,data:B9hfieO81ucwU3VF,iv:DguzfTC4lslGYQbJ2v5GYx8YLGlQHhO4ILM80IZhDzc=,tag:Jyaj40ZBRmGwYhq12xyb8g==,type:str]
    replicas: ENC[AES256_GCM,data:VA==,iv:LN+oZrU+FMjwF2aYnh5HHkZ6FpSlPFfzpTV0TO1EFt0=,tag:NM1LF2GtYjrqLlXPHQlcUg==,type:int]
    additionalEnv: {}
    volumes:
        data:
            size: ENC[AES256_GCM,data:4CDuLqc=,iv:BwneAY4wi0RI6DeUjzRNT663Fbmrk55hEL1M+qBf9oY=,tag:Dh+cI/rRPj2/+eYhJlFK+g==,type:str]
            storageClass: ENC[AES256_GCM,data:IZ+akeXWIBZFVA==,iv:iSf2+xJTyvndzDwnD8Hz9XSLT3AwlmFnuntL6TH9oTQ=,tag:Vg4WulRb9kXw78U02bUL9Q==,type:str]
            #ENC[AES256_GCM,data:swkm12Jh0Wuga1qXk5ZE6q65aX9ZGTHB1NA=,iv:OYixw0DSVeUTXxkBe2d5+iGaVWwQwXXNmog3S2ZlNgk=,tag:SVgnVo7UKOP7/JvkS2HCCQ==,type:comment]
    service:
        type: ENC[AES256_GCM,data:uSpCo280js8j,iv:UFxal4LAX0lCR6AQ9jkssOKytQMvuT8teVAId6REMdo=,tag:oZ4a1U85eMcjKd2vgOjqVw==,type:str]
        #ENC[AES256_GCM,data:a7lP8z0ubjq+DgGy8g==,iv:qtOB++ZylHVkgDZd+9O5eXwuCRNmKtlSjdg0AxMORYs=,tag:PzDp1oBO/03pM3KASsTdQg==,type:comment]
#ENC[AES256_GCM,data:lt1LUBVyp036BQ==,iv:l4PnpMz7O0aGgsCOi9MrUyfiL+AJ6rvQfjCUZihrKJ0=,tag:gk6MgJYny5WxVrSsvqBKew==,type:comment]
#ENC[AES256_GCM,data:IuarHKMs6Rc=,iv:Htkdez08zKx21iNb2AJuHZWvn611mFytRFwZVlt0Y/M=,tag:s7KFRrAwSBMKKzbggLsAlA==,type:comment]
#ENC[AES256_GCM,data:GoluZk3XjppEnWL9,iv:AO/4227/VyrzQT2JP6RqLTjbI9+AS9oz9JwJsUwoOsU=,tag:3kUQUcd8TOEH4yJfIig8Xg==,type:comment]
#ENC[AES256_GCM,data:jM+MlBmxr/k=,iv:uYM857PvbSf1X2Vr6JoZ/BiBIJY2I519ijG5tHIBfVA=,tag:+kqY4uNJLFf2TCfiLjUr5w==,type:comment]
#ENC[AES256_GCM,data:mEkzcCt/kYaJDzWhQQ==,iv:pw2z/c29GVy1+xOuXqtysIpU0RQBfH65hHyo7VcEtV8=,tag:hBQFLWVsxPGg1dn4zHqbUA==,type:comment]
rpc:
    credentials:
        rpcUser: ENC[AES256_GCM,data:+hgBSqVG,iv:dzVne5UW3QDMDbDxSW4xiw8SWyJIeHt9ZVzaaifxsGc=,tag:T/M+Q9GfbmOW1O83g+7zVA==,type:str]
        rpcPassword: ENC[AES256_GCM,data:Cl+VBUQlFPjCV0CByQKs,iv:upxWo3jg4e6Y92tzkdgjMAmuG+fQdlcODrghlwPhEA4=,tag:Y73WBw17k4cVxBMqLBfwow==,type:str]
lightwalletd:
    enabled: ENC[AES256_GCM,data:meI5ag==,iv:MegZwkPv3rOUsDvLEs+J8ve43o4Q5LRvgpAGuB96qBs=,tag:hhiox2rr/80N2p0vv8PQCA==,type:bool]
    #ENC[AES256_GCM,data:/Z9ZZD085p9MDx0QCTyGnA==,iv:1357glmCN+BIbsnU4PM9DHhH5YQyxPuSbNH8rKtgycw=,tag:atFQ1BVJpy+olYmtJYo/hg==,type:comment]
    zcashNodeType: ENC[AES256_GCM,data:f85T5ys=,iv:dR/pmrkyvojgHKN3cawDxejuC3B943OG99I+qU+sMLA=,tag:zQqHtJqc66s1A1De8a83xQ==,type:str]
    name: ENC[AES256_GCM,data:RhJvu6zNVmAxIwbj,iv:CIBeDA2o9v1/Pnu4+8264Dp8UZTzovJSvToM+oUtYjA=,tag:cdRV0d/bndty8ol/iBtbNA==,type:str]
    image:
        repository: ENC[AES256_GCM,data:TyVyk+YVvrrc1Nig6bqyaI1XgqTG0EcP1noj,iv:QS7tjqG1yoBUVJBIMIA5lo2r86f3OEDsPiIQUTojbEs=,tag:g7Gy5FeyViuBK7rLkdWqQg==,type:str]
        tag: ENC[AES256_GCM,data:J+6vdunP,iv:hDXaryDWJIYQbgNo2CHavst+zPYO4UU2E/zIrBCkkOg=,tag:5j9XALASUwOqZbpyXaNPMA==,type:str]
        pullPolicy: ENC[AES256_GCM,data:c4JGqspb/hUJN3Vs,iv:t4VMPARtiffTOeh8GmThhLeTHbtzhrtoxMOTTXgKEFw=,tag:gMmexns15k12iK6BGF4erQ==,type:str]
    replicas: ENC[AES256_GCM,data:hA==,iv:FlgieBSl0S/WI3taFfZkoXbJI6wv+c7VGhSJeBhszI4=,tag:7sv1L6XVU++CU4tauQVH8w==,type:int]
    additionalArgs: []
    volumes:
        data:
            size: ENC[AES256_GCM,data:8cSObtc=,iv:37sv5kNIRdM22h5T7clq4Y8Xa66QW95sD7iJ/eCfC8o=,tag:6beKNnJNZZTvm/dTB+Hwpg==,type:str]
            storageClass: ENC[AES256_GCM,data:Y6MEfXVqjmQjLg==,iv:lM0UE8NHDF3gphV4OCR8FYZTe8HSMuUz016xpIKVjbw=,tag:ECzKs/Sdey4oqvv/gxxuLw==,type:str]
    service:
        type: ENC[AES256_GCM,data:lztymhMjuec0,iv:Y5HSUGEXH+FqPMSEA/eNWd4WI8C7hTWc3mMtkGZ+D9Y=,tag:xVdfW5wmjXLS8ZhR8lZYaw==,type:str]
    requests: {}
    #ENC[AES256_GCM,data:8xXObmpgss1U,iv:f7GLDUpKF2tdDj1dPvB+yDsGcGFT2GkojY+jtgB53UE=,tag:ArLWzLwTiTJS0a2sbJr5oQ==,type:comment]
    #ENC[AES256_GCM,data:9fQzNrNafbgk,iv:+dRMar2T7EGbUMR4CXV0GukplPxBL6ZHzRt1r1ZK4w4=,tag:xB2h4XPwqhCaeE5fJhswgw==,type:comment]
    #ENC[AES256_GCM,data:RGWAZlLFncKd6DcDWw==,iv:taR1NGcas68CPRjgumvwmoKZDbNO3sveeMIktp3qE+E=,tag:y3Cnv9V8GrWxZ6+pKZtlcQ==,type:comment]
    #ENC[AES256_GCM,data:1ZT4aOLdEg==,iv:M+7awifItqMZ2SSDMx/TD6wq/Ys4J/NrYY2s6OY3ozU=,tag:lS11HkXZgjD6eGxv9gUMSg==,type:comment]
    #ENC[AES256_GCM,data:Gv4bouihPEJbuCEa,iv:ZUrXMoIr8Cq4QNTkwZ3Tk172cxebwZwAxKFZ6WwmzGY=,tag:xUVu3grErlg8xkHFnEX2yw==,type:comment]
#ENC[AES256_GCM,data:YmZKDy21IUtEmTwlPL4CfHGBFg==,iv:TINJIKlVg0r36/9me2fZ0tlpLDOQGaFoiU2WxZiDLbA=,tag:S0CJEU5CQtR6Q7DcXVNCTA==,type:comment]
caddy:
    enabled: ENC[AES256_GCM,data:K3Yor9M=,iv:CelvAK6AUEy4F/WlYEhpXBRUUfnGm53gn6hZ/3aLSZs=,tag:xYhB3Iv/NmvdVlDC/QyjNw==,type:bool]
    domain: ENC[AES256_GCM,data:Q52myPugnwxXJJ0Xwz95,iv:z0bS8f+RhE2/QGFRXFX/AnP0m0PZfnMFPe9SP+DkiNM=,tag:6JJXDhQpIhfqldI86/H1LQ==,type:str]
    email: ENC[AES256_GCM,data:YkYsXnouQYVwfeKqtT6kcV0=,iv:26SHfUabe+xzqV69Kxl+X/muEjg5lzw5/8U7Vp+04u0=,tag:udfJT678nB+Vbb4GwNSIow==,type:str]
dnsseeder:
    enabled: ENC[AES256_GCM,data:4xJ9PQ==,iv:/8Wyy+n1JmE2593/IyFuzLOANznbvB1ALEZx0gfE7t0=,tag:MIMYsZUR76jClR04qCWO9Q==,type:bool]
    name: ENC[AES256_GCM,data:1S2JhDv89sxp,iv:3Ni6hpt7qYQz4k0JZoRdNRL29A1W+1LhbpHdrvanKzA=,tag:ADvhGj+jPlfBVv85WXPcHQ==,type:str]
    replicas: ENC[AES256_GCM,data:ug==,iv:SdDhnOHYG5bPe8i6IPqvu5d/oW8L3FmTHdhQ0jP4L/k=,tag:gDkrhYw9AwgEkPzehpVCRg==,type:int]
    image:
        repository: ENC[AES256_GCM,data:cu3Zo6ve0ZCL7dp4N0uyz0wVcvkGjY8M,iv:4nT/bLfnZzBL2ygzwtnMy1YIK5KZPCQJdpPWFjuZ3yo=,tag:98wI1M7tFJ5ElQPHL8/QOg==,type:str]
        tag: ENC[AES256_GCM,data:SQRbdOTB,iv:hJ+KYy+BM0007Kw0Ox8UhK/rcLC/NlX4XohWyDb71kU=,tag:12HYp/AOUi0SpjyuTHLovg==,type:str]
        pullPolicy: ENC[AES256_GCM,data:m5c4GzkaRvyYVV0n,iv:0AnVblZlA887PTMaWjXC+UDjS9FnSXc7ToL7crGF8sk=,tag:OQmKQltmarS7P5EsfO7y7Q==,type:str]
    service:
        type: ENC[AES256_GCM,data:sFISKtYLd5Oq,iv:skAka4bMSvIz6l6Y1qnLMWt+byxFoDYMIkl4VNpLAZU=,tag:J8aWH4m3uAs6VU1GL85TkQ==,type:str]
    requests: {}
    #ENC[AES256_GCM,data:B3ihpdhm1c41Pg==,iv:FJwd8GLQKwlMQ/iKPP8Lx2an7ZEoRJgdtXwAI2j47VM=,tag:nDF8W4PUMc9jUnCNmUT/eg==,type:comment]
    #ENC[AES256_GCM,data:BPcdEENCVF/7,iv:oLFgtvee5wAkzQkII6mvqiQvVTyphfutbRudTft1ydc=,tag:YnJ7SIzoW2osNoa2e2CsBg==,type:comment]
    #ENC[AES256_GCM,data:W7qRqyZP8vcoZFLavBl7Tg==,iv:HOH0XKWi5xO6Zn+I4FDhGRpclI5vE6aPlIjzSfC6BRE=,tag:ERsFijC/xVU5Zl76BOzOuw==,type:comment]
    #ENC[AES256_GCM,data:1IiRqrnWKA==,iv:YiI2HaUUGZfMNFWxY8GNco/8ElcDGl59v2AGcGboArs=,tag:U+1ySNBDIhNw0sCq0vWkzw==,type:comment]
    #ENC[AES256_GCM,data:DOetze3JnDukCuBh8g==,iv:jMfqLHYnzs4TEOi7nQ9MZfXDvlSQUTvxnlSaA03RY+I=,tag:e2B4dPVRPjKQ367DtNMnWQ==,type:comment]
    env:
        seedHostname: ENC[AES256_GCM,data:A2PMqOOkmAQ3eY+t8Vw=,iv:1fN8KQLWVHHHfUdk/ny26+WVd+Najri8ggCgdzE2QMo=,tag:aym7Pd3AGl3ICq4HZDnixg==,type:str]
        nodeHostname: ENC[AES256_GCM,data:XDwlHcZDEMVmhCDcGb+kSvCLw94=,iv:j/ooFzKs/hOkIB3Rlir4/tD6XZjklmD84LYd75PMMyI=,tag:VvloAaVnloegkJBwBmWoBg==,type:str]
        email: ENC[AES256_GCM,data:aZrSzl8a97Xi9/+qDfjD9yrX0lkqlacaXA==,iv:eQ/KyjBzo1Biuep0iypt1StqMeQvSTaMDkYF19V4wNA=,tag:61HtTr8bBYwTeS46iWtE3w==,type:str]
        threads: ENC[AES256_GCM,data:4WyY,iv:XELHBpgfUaw8oOR1IIdLPbEYTrbGKGevMdeg4w+ReZI=,tag:FPqecg3J39znhl7iXYOevA==,type:int]
        address: ENC[AES256_GCM,data:XAnf2JLi9g==,iv:aN94oxe6rSczE7lv3EXYI4p+y6d3vyrepZyRHTtUzTE=,tag:uRKc07ooOxABIPMs6pXSYQ==,type:str]
        network: ENC[AES256_GCM,data:+YL9vsJ+8Q==,iv:A9pjxawa/bZaAQ9gITwf5elWXixHUDav5AHMWMJi1uw=,tag:9rkLlWJ33+e86jZdDLtKFQ==,type:str]
sops:
    age:
        - recipient: age1fu3yw8700dznl0xgsrcgghjase8uh94unaj4pjjkh70g7kzv8u3sqcgz4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobjJLK1hneVkvUVo0ZnVO
            SVdiSVQvbDBTMkhGSDB6dzEvR1RLTGpnQUVjCmJSbGFWa3MyZVVML2dRUWZ3QjZU
            YXFJVTZDeXBZR1ZwWnZ4ZjFoQUU5VFkKLS0tIEMwNmdhQkRqekpmUTNGb1hIU2RF
            SC80RXRlcWFScDBXMm5CbWVDQ25nYUUKxk9xJ+deUzlBT+Z7gpcSdoOMnI7t4877
            fVGV3U8lK/OI86Pa31Yp5FMdBEDHrsREq18fbJKiOetQRR1//zIToA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T06:36:13Z"
    mac: ENC[AES256_GCM,data:KIfWB7lqwn5BjpodTWvUhF5BZVeS0+eG3QNWn1equteOIcG2SiEaUKAfxcwS2QI336HsBFZIODCV8TBDZ0bk0euiXxKaZStD03Brfs8061A+H1+qvNYprGzPx6seYlsL2Tf+XlwFF9wvHYvDuBZ7YpTykAq3rZnYIAvU4joy+Jo=,iv:IxPeHHgMWKPScH0+QDGu+I0NH0ucHTYee2RE617hUb8=,tag:DijGi8HT26O0MTJaGOB1VA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
