apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zcash-stack
  namespace: zcash 
spec:
  interval: 30m
  chart:
    spec:
      chart: zcash-stack 
      version: "1.0.3"  


      sourceRef:
        kind: HelmRepository
        name: zcash-stack 
        namespace: zcash 
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: Secrets 
      name: zcash-stack-secrets 

  values:
    Global:
      nodeSelector:
        hostname: highpower
    
    zebra:
      volumes:
        data:
          storageClass: local-path
    lightwalletd:
      volumes:
        data:
          size: 350Gi
          storageClass: local-path
    
    dnsseeder:
      env:
        seedHostname: "sirius-sec.com"
        nodeHostname: "zcash.sirius-sec.com"
        email: "sirius-sec@protonmail.com"
        
