apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zcash-stack
  namespace: zcash 
spec:
  interval: 30m
  chart:
    spec:
      chart: zcash-stack 
      version: 1.* 
      

      sourceRef:
        kind: HelmRepository
        name: zcash-stack 
        namespace: zcash 
      interval: 12h
  
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  
  valuesFrom:
    - kind: Secret
      name: zcash-stack-secrets
      valuesKey: rpc-password
      targetPath: rpc.credentials.rpcPassword
    
    - kind: Secret
      name: zcash-stack-secrets
      valuesKey: rpc-password
      targetPath: rpc.credentials.rpcUser 

  values:
    nodeSelector:
      hostname: highpower
    dnsseeder.env.seedHostname: "sirius-sec.com"
    dnsseeder.env.nodeHostname: "zec.sirius-sec.com"
    dnsseeder.env.email: "sirius-sec@protonmail.com"

