apiVersion: v1
kind: Secret
metadata:
    name: zcash-stack-secrets
    namespace: zcash
stringData:
    #ENC[AES256_GCM,data:IUVvtGvcwK8SH6jOipJKyEV09VtXqCuVutBMyWoG,iv:ZmZCWyE5yiEakX3YkJnuw+JdrSQitmnxAxLsM//U/TI=,tag:XVAuyF7ad+0Gv9pjtoZF4Q==,type:comment]
    rpc-user: ENC[AES256_GCM,data:22TMenC4,iv:OrejlTUcBXFqtF+zO1FP/pWDD5ILp7WFFBt+PzVwrg8=,tag:GRl5hJ2N4N5Ad9fNqVUHWg==,type:str]
    #ENC[AES256_GCM,data:XESjYj+AU+nBr15o7lkThzHofOdAbi/ryMxzYkED,iv:tVd7mtpCxBuq18FFfJrP4Iqj1THHbR9t+5bS/48sn8c=,tag:2ybZWlzaGBNEkAl6E9D6QQ==,type:comment]
    rpc-password: ENC[AES256_GCM,data:Uhx+vYPXNNLg0Fo=,iv:MhxN5s5UMDClPklBNVAnmiW4uxGUZLMsSJ/g4Nf+Jvg=,tag:pmOwyFvq5QXNF1edY3NNTw==,type:str]
sops:
    age:
        - recipient: age1fu3yw8700dznl0xgsrcgghjase8uh94unaj4pjjkh70g7kzv8u3sqcgz4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZ1JJSDkrTlRyL0l0NERJ
            bG1nRXprdDJTRVVLT3NsVkZHMHo1K2FTbFZVCjhHOVFIakJLZkUvdXVvaXk3a0Vp
            YndtQUU5V0tmK0lNdUtmOU9nMjBIUUkKLS0tIGtGaURUWVBLYW5tL3hURERhVlRN
            N2pnNEJSd1k2ckNwQ1pJcEtLNjJsSGMKGqWx3zfpyixCHZfidGzLCjGfpbEuIsoe
            jUPrJx92AsAqKWJ+Hi24sWrmBwqTU9Z2BWvb6yalYoqAyWOABw7IfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T02:20:42Z"
    mac: ENC[AES256_GCM,data:6KDTW7GI7U0PRSc3lmFXlCZE6SyL8AmrdQM7Ypc0BluDfbwwmZChTWfqzEWN9vdfrOBU+m55pKk0y9OyGsO6n1k2vaTCGhQd1R+C4BXiqkuI3DGFxtawhtJScf9gS8Avf0TIE47+WOka6pyUTzZK2HcEL5TcKDcoN5b5bVy3bC0=,iv:Po2Ob8js9Il94B5cFzXYa/muRcZpPmzAD6AR6PRI4Fk=,tag:mryRrJCQjRGR3hjCgkxSmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
