zcashd:
  enabled: False
  name: zcashd
  testnet: False
  image:
    repository: electriccoinco/zcashd
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  reindex: False
  nodes:
   - mainnet.z.cash
  additionalArgs: []
  volumes:
    data:
      size: 400Gi
      storageClass: local-path
      accessMode: ReadWriteOnce 
  service:
    type: ClusterIP
  requests: {}
  # requests:
  #   cpu: 1
  #   memory: 1.5Gi
  #limits:
  #  memory: 3Gi

zebra:
  enabled: True
  name: zebra
  testnet: false
  image:
    repository: zfnd/zebra
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  additionalEnv: {}
  volumes:
    data:
      size: 400Gi
      storageClass: local-path
      #accessMode: ReadWriteOnce 
  service:
    type: ClusterIP
  # requests: {}
 # requests:
   #  cpu: 2
    # memory: 4Gi
   # limits:
    # memory: 16Gi

rpc:
  credentials:
    rpcUser: sirius
    rpcPassword: petuk1k1711666! 

lightwalletd:
  enabled: true
  zcashNodeType: zebra # zebra or zcashd
  name: lightwalletd
  image:
    repository: electriccoinco/lightwalletd
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  additionalArgs: []
  volumes:
    data:
      size: 400Gi
      storageClass: local-path 
  service:
    type: ClusterIP
  requests: {}
   #requests:
    # cpu: 0.5
     #memory: 512Mi
  #limits:
   # memory: 3Gi

# lightwalletd-front
caddy: 
  enabled: False
  domain: "lwd.example.com"
  email: "admin@example.com"

dnsseeder:
  enabled: True
  name: dnsseeder
  replicas: 1
  image:
    repository: electriccoinco/dnsseeder
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  requests: {}
  # requests:
  #   cpu: 1
  #   memory: 1.5Gi
  #limits:
  #  memory: 3Gi
  env:
    seedHostname: "sirius-sec.com"
    nodeHostname: "zcash.sirius-sec.com"
    email: "sirius_sec@protonmail.com"
    threads: 384
    address: "0.0.0.0"
    network: "mainnet"

