apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lightwallet-certs
  namespace: zcash # Or your application's namespace
spec:
  secretName: lightwallet-certs 
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer # or Issuer
  encodeUsable: true
  commonName: "*.sirius-sec.com"
  dnsNames:
    - "zcash.sirius-sec.com"
