apiVersion: v1
data:
    zcash.conf: ENC[AES256_GCM,data:4sQ2Jo5Zy3r56vrEhc0yNYo6AYAS7UfcDSrYqZetPmFYWCz9fOSxu28MSJwD4KdcrzXn/L635+UARYbyLWV3PxrWkLU=,iv:caZ6Z715fEVJtQDA82kEMrJa+EHOUX/KEE9JaOudDQg=,tag:RG/sLlJNWijsjPdwYyc46w==,type:str]
kind: Secret
metadata:
    name: zcash-stack-lightwalletd
    namespace: zcash
sops:
    age:
        - recipient: age1fu3yw8700dznl0xgsrcgghjase8uh94unaj4pjjkh70g7kzv8u3sqcgz4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NWVNWEN2dzFzWGtveGxO
            MSt5UXJJTXZPbXlDa0IzMWd5Ymt5SjZTeXdFCnNOcW9vZE50aUJmcGs4U3lpOGdW
            UGFXb2o5cW1pWk5WbjJJakRUV2tjd3MKLS0tIHNqT1k1THFiMUFUeXBOc1lYL1Nx
            YWFrNWcyazJ3cjhlWTRpQzNSbFI1bXMKAO3GjJtAhg0dFXDcGVpfFcMHsYWSd7Cg
            8G0uU7mIbMIKBC2dYORsUAB0Lqi0cMKzVoOQriEhSDm10sMjwqMdBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T01:02:39Z"
    mac: ENC[AES256_GCM,data:Wz7Jf0gdrnx0lLXy5WhWY0FOJod7b7Rc5NJzVd6SRij9MvdwPrTpBqmi1N2TfaXc3XVHLckCe6h6f/lqnCA68qoJOq7kHUFc3wu2ldZzckEJjfgK1bSxqGGJ3Z4dydlhORdHbqR7woojViL8WH6/ZLi9/ofRf7Cds85yVz79d5c=,iv:Eu7ag4vII/+P2f3eXp/0sLSpaM+EfJjVSDxE1E+rFUE=,tag:UtYn6z1Oq6gFnEoBjd1P6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
