apiVersion: v1
kind: Secret
metadata:
  name: lightwalletd-config-secret
  annotations:
    # Flux/SOPS specific annotation to enable automatic decryption
    kustomize.toolkit.fluxcd.io/encrypted: "true"
type: Opaque
stringData:

  zcash.conf: |

  {
	  "data": "ENC[AES256_GCM,data:YBA3wkrwXg2XkjSQnC/yLPD75oERX2c8T5camYiXuLraVhUc8GtvM0NsGeZuPkaduoRTPjQxcBw3OvttPyhWXJEYylgN0VNMmwCGCNwT+/cGvSzmKt1K+sp8wcxHEpJGncfd95QyB2hKoYvUZGvHISFi0tCuh6DZN8g/be8YRLITEGIvkPMBa/fVwlKqkYA0TQ==,iv:2riRbT7S9k+mPqa4pczcQvIPiqFeeegbmYkXTTTUOr4=,tag:50zelyXsPd3FVJgS8Q2JmQ==,type:str]",
	  "sops": {
		  "age": [
			  {
			  	"recipient": "age1fu3yw8700dznl0xgsrcgghjase8uh94unaj4pjjkh70g7kzv8u3sqcgz4d",
			  	"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MkNqYWRtUUpMNEo3Zkpz\nWnA4RVFWYUJvM3NwdkZBM0ZrUUdZQmpaVlhjCmVidWdlS2hDNUFPOC9xM0pBOWk4\nYUFCTG9jamJNdVZab3pNOUhnZktpM1EKLS0tIEVFQ3lVV21tcDIrNU9TWXBwVWZm\nK0lHM3pzL29hUU5pQUFUMHBSMC9xN1EKhkiCSYsWA3p7djdMscHHxUChugdLNNdn\nUCZVBXjcOzQ53HhcwkL61YQYn9eFfUAHPPYO+WFWz8Ha9mE99rqseA==\n-----END AGE ENCRYPTED FILE-----\n"
		  	}
	  	],
	  	"lastmodified": "2025-11-29T02:32:31Z",
	  	"mac": "ENC[AES256_GCM,data:ptQRy2BgQnb7YwOx3XS2St94OTuzwN5tubTRudyyvs7uZH/xWswaHY3b+3f9IhceOS6o3Flo12I99QQSDK2BVK2ctFFj28B+FWpcU8XSOFWa9/mW0ZfL4nlZoN4IEcDyZ9I2RoP7zhEMELcMvIAWuFxLRCc5pDhrTbH5Lnc7hQM=,iv:+GNp0NxuYutPhfQxiguYNB7jpfMWfbjDPnq6t4dYoEw=,tag:vPjDDN0sOEMpqzYC2RIQzw==,type:str]",
	  	"version": "3.11.0"
	  }
     }
