apiVersion: v1
kind: Service
metadata:
  name: lightwallet-service
  namespace: zcash
  labels:
    app: zcash-stack-lightwallet
spec:
  selector:
    app: zcash-stack-lightwalletd 
  ports:
    - name: http
      protocol: TCP
      port: 9067
      targetPort: 9067


