apiVersion: v1
kind: Service
metadata:
  name: linkding-service
  namespace: linkding

spec:
  type: ClusterIP
  selector:
    app: linkding
ports:
    - protocol: TCP
      port: 9090
      target: 9090
    
